[package]
name = "groupls2"
version = "0.1.0"
authors = ["ironmagma"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.8.0"
clap = "2.33.0"

#[[bin]]
#name = "groupls2"
#path = "src/main.rs"
