[package]
name = "groupls"
version = "1.0.0"
authors = ["philip-peterson"]
edition = "2018"

[dependencies]
itertools = "0.8.0"
serde = "1.0.101"
serde_json = "1.0"
serde_derive = "1.0.101"

[[bin]]
name = "groupls"
path = "src/main.rs"
